version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
  reviewers:
  - chvp
  groups:
    rubocop:
      patterns:
        - "rubocop*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
  reviewers:
  - chvp
