require: 
  - rubocop-minitest
  - rubocop-rails

AllCops:
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "node_modules/**/*"
  TargetRubyVersion: 3.1
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Enabled: false

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Max: 4
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: annotated
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/MultilineBlockChain:
  Enabled: false
