name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: "test"
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v17
        with:
          name: accentor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true
      - name: "Setup database"
        run: |
          nix develop --command pg:start
          nix develop --command rails db:setup
      - name: Run tests
        env:
          CI: true
        run: nix develop --command rails test
      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v17
        with:
          name: accentor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true
      - name: Lint with rubocop
        env:
          RAILS_ENV: "test"
        run: nix develop --command rubocop -c .rubocop.yml -f github
      - name: Scan with brakeman
        run: nix develop --command brakeman --no-pager
