name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: "test"
      DATABASE_URL: "postgres://postgres:accentor@127.0.0.1:5432/accentor"
    services:
      postgresql:
        image: postgres
        env:
          POSTGRES_PASSWORD: "accentor"
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Cache Ruby dependencies
      uses: actions/cache@v2
      with:
        path: /usr/local/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Install dependencies
      run: |
        bundle config path
        bundle install --jobs 4 --retry 3
    - name: Run tests
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bundle exec rails db:setup
        bundle exec rails test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Cache Ruby dependencies
      uses: actions/cache@v2
      with:
        path: /usr/local/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Install dependencies
      run: |
        bundle config path
        bundle install --jobs 4 --retry 3
    - name: Lint with rubocop
      env:
        RAILS_ENV: "test"
      run: |
        bundle exec rubocop -c .rubocop.yml
